/********************************************************************************
 * Copyright (c) 2022-2023 Sensmetry UAB and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is
 * available at https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/

export const STDLIB = {
    version: "2023-02",
    tree: "https://github.com/Systems-Modeling/SysML-v2-Release/blob/2023-02/sysml.library/",
    raw: "https://raw.githubusercontent.com/Systems-Modeling/SysML-v2-Release/2023-02/sysml.library/",
    files: [
        "Systems Library/Actions.sysml",
        "Systems Library/Allocations.sysml",
        "Systems Library/AnalysisCases.sysml",
        "Systems Library/Attributes.sysml",
        "Systems Library/Calculations.sysml",
        "Systems Library/Cases.sysml",
        "Systems Library/Connections.sysml",
        "Systems Library/Constraints.sysml",
        "Systems Library/Interfaces.sysml",
        "Systems Library/Items.sysml",
        "Systems Library/Metadata.sysml",
        "Systems Library/Parts.sysml",
        "Systems Library/Ports.sysml",
        "Systems Library/Requirements.sysml",
        "Systems Library/StandardViewDefinitions.sysml",
        "Systems Library/States.sysml",
        "Systems Library/SysML.sysml",
        "Systems Library/UseCases.sysml",
        "Systems Library/VerificationCases.sysml",
        "Systems Library/Views.sysml",
        "Kernel Libraries/Kernel Semantic Library/Base.kerml",
        "Kernel Libraries/Kernel Semantic Library/Clocks.kerml",
        "Kernel Libraries/Kernel Semantic Library/ControlPerformances.kerml",
        "Kernel Libraries/Kernel Semantic Library/FeatureReferencingPerformances.kerml",
        "Kernel Libraries/Kernel Semantic Library/KerML.kerml",
        "Kernel Libraries/Kernel Semantic Library/Links.kerml",
        "Kernel Libraries/Kernel Semantic Library/Metaobjects.kerml",
        "Kernel Libraries/Kernel Semantic Library/Objects.kerml",
        "Kernel Libraries/Kernel Semantic Library/Observation.kerml",
        "Kernel Libraries/Kernel Semantic Library/Occurrences.kerml",
        "Kernel Libraries/Kernel Semantic Library/Performances.kerml",
        "Kernel Libraries/Kernel Semantic Library/SpatialFrames.kerml",
        "Kernel Libraries/Kernel Semantic Library/StatePerformances.kerml",
        "Kernel Libraries/Kernel Semantic Library/Transfers.kerml",
        "Kernel Libraries/Kernel Semantic Library/TransitionPerformances.kerml",
        "Kernel Libraries/Kernel Semantic Library/Triggers.kerml",
        "Kernel Libraries/Kernel Function Library/BaseFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/BooleanFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/CollectionFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/ComplexFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/ControlFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/DataFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/IntegerFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/NaturalFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/NumericalFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/OccurrenceFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/RationalFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/RealFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/ScalarFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/SequenceFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/StringFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/TrigFunctions.kerml",
        "Kernel Libraries/Kernel Function Library/VectorFunctions.kerml",
        "Kernel Libraries/Kernel Data Type Library/Collections.kerml",
        "Kernel Libraries/Kernel Data Type Library/ScalarValues.kerml",
        "Kernel Libraries/Kernel Data Type Library/VectorValues.kerml",
        "Domain Libraries/Requirement Derivation/DerivationConnections.sysml",
        "Domain Libraries/Requirement Derivation/RequirementDerivation.sysml",
        "Domain Libraries/Quantities and Units/ISQ.sysml",
        "Domain Libraries/Quantities and Units/ISQAcoustics.sysml",
        "Domain Libraries/Quantities and Units/ISQAtomicNuclear.sysml",
        "Domain Libraries/Quantities and Units/ISQBase.sysml",
        "Domain Libraries/Quantities and Units/ISQCharacteristicNumbers.sysml",
        "Domain Libraries/Quantities and Units/ISQChemistryMolecular.sysml",
        "Domain Libraries/Quantities and Units/ISQCondensedMatter.sysml",
        "Domain Libraries/Quantities and Units/ISQElectromagnetism.sysml",
        "Domain Libraries/Quantities and Units/ISQInformation.sysml",
        "Domain Libraries/Quantities and Units/ISQLight.sysml",
        "Domain Libraries/Quantities and Units/ISQMechanics.sysml",
        "Domain Libraries/Quantities and Units/ISQSpaceTime.sysml",
        "Domain Libraries/Quantities and Units/ISQThermodynamics.sysml",
        "Domain Libraries/Quantities and Units/MeasurementRefCalculations.sysml",
        "Domain Libraries/Quantities and Units/MeasurementReferences.sysml",
        "Domain Libraries/Quantities and Units/Quantities.sysml",
        "Domain Libraries/Quantities and Units/QuantityCalculations.sysml",
        "Domain Libraries/Quantities and Units/SI.sysml",
        "Domain Libraries/Quantities and Units/SIPrefixes.sysml",
        "Domain Libraries/Quantities and Units/TensorCalculations.sysml",
        "Domain Libraries/Quantities and Units/Time.sysml",
        "Domain Libraries/Quantities and Units/USCustomaryUnits.sysml",
        "Domain Libraries/Quantities and Units/VectorCalculations.sysml",
        "Domain Libraries/Metadata/ImageMetadata.sysml",
        "Domain Libraries/Metadata/ModelingMetadata.sysml",
        "Domain Libraries/Metadata/ParametersOfInterestMetadata.sysml",
        "Domain Libraries/Metadata/RiskMetadata.sysml",
        "Domain Libraries/Geometry/ShapeItems.sysml",
        "Domain Libraries/Geometry/SpatialItems.sysml",
        "Domain Libraries/Cause and Effect/CausationConnections.sysml",
        "Domain Libraries/Cause and Effect/CauseAndEffect.sysml",
        "Domain Libraries/Analysis/AnalysisTooling.sysml",
        "Domain Libraries/Analysis/SampledFunctions.sysml",
        "Domain Libraries/Analysis/StateSpaceRepresentation.sysml",
        "Domain Libraries/Analysis/TradeStudies.sysml",
    ],
} as const;
